//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ACMEEntities : DbContext
    {
        public ACMEEntities()
            : base("name=ACMEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LLAMADA> LLAMADA { get; set; }
        public virtual DbSet<CALL_CENTER> CALL_CENTER { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<CUENTA> CUENTA { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIO { get; set; }
        public virtual DbSet<PLANTA> PLANTA { get; set; }
        public virtual DbSet<PROBLEMA> PROBLEMA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<SOLUCION> SOLUCION { get; set; }
        public virtual DbSet<CLIENTEXCUENTAXPRODUCTO> CLIENTEXCUENTAXPRODUCTO { get; set; }
        public virtual DbSet<COMPRAXCLIENTE> COMPRAXCLIENTE { get; set; }
        public virtual DbSet<EMPLEADOXCALLCENTER> EMPLEADOXCALLCENTER { get; set; }
    
        public virtual int LLAMADA_DELETE(Nullable<int> iD_LLAMADA)
        {
            var iD_LLAMADAParameter = iD_LLAMADA.HasValue ?
                new ObjectParameter("ID_LLAMADA", iD_LLAMADA) :
                new ObjectParameter("ID_LLAMADA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LLAMADA_DELETE", iD_LLAMADAParameter);
        }
    
        public virtual int LLAMADA_UPDATE(Nullable<int> iD_LLAMADA, Nullable<System.DateTime> fECHA_LLAMADA, Nullable<short> fOLLOW_UP, Nullable<short> eSTADO_RESOLUCION_LLAMADA)
        {
            var iD_LLAMADAParameter = iD_LLAMADA.HasValue ?
                new ObjectParameter("ID_LLAMADA", iD_LLAMADA) :
                new ObjectParameter("ID_LLAMADA", typeof(int));
    
            var fECHA_LLAMADAParameter = fECHA_LLAMADA.HasValue ?
                new ObjectParameter("FECHA_LLAMADA", fECHA_LLAMADA) :
                new ObjectParameter("FECHA_LLAMADA", typeof(System.DateTime));
    
            var fOLLOW_UPParameter = fOLLOW_UP.HasValue ?
                new ObjectParameter("FOLLOW_UP", fOLLOW_UP) :
                new ObjectParameter("FOLLOW_UP", typeof(short));
    
            var eSTADO_RESOLUCION_LLAMADAParameter = eSTADO_RESOLUCION_LLAMADA.HasValue ?
                new ObjectParameter("ESTADO_RESOLUCION_LLAMADA", eSTADO_RESOLUCION_LLAMADA) :
                new ObjectParameter("ESTADO_RESOLUCION_LLAMADA", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LLAMADA_UPDATE", iD_LLAMADAParameter, fECHA_LLAMADAParameter, fOLLOW_UPParameter, eSTADO_RESOLUCION_LLAMADAParameter);
        }
    
        public virtual ObjectResult<LLAMADAGetById_Result> LLAMADAGetById(Nullable<int> iDLLAMADA)
        {
            var iDLLAMADAParameter = iDLLAMADA.HasValue ?
                new ObjectParameter("IDLLAMADA", iDLLAMADA) :
                new ObjectParameter("IDLLAMADA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LLAMADAGetById_Result>("LLAMADAGetById", iDLLAMADAParameter);
        }
    
        public virtual ObjectResult<LLAMADASGETALL_Result> LLAMADASGETALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LLAMADASGETALL_Result>("LLAMADASGETALL");
        }
    
        public virtual ObjectResult<Nullable<decimal>> LLAMADASinsert(Nullable<int> iD_Llamada, Nullable<System.DateTime> fecha_Llamada, Nullable<short> follow_UP, Nullable<short> estado_Resolucion_Llamada, Nullable<int> iD_CLIENTE, Nullable<int> iD_EMPLEADO, Nullable<int> iD_PRODUCTO, Nullable<int> iD_PROBLEMA, Nullable<int> iD_SOLUCION)
        {
            var iD_LlamadaParameter = iD_Llamada.HasValue ?
                new ObjectParameter("ID_Llamada", iD_Llamada) :
                new ObjectParameter("ID_Llamada", typeof(int));
    
            var fecha_LlamadaParameter = fecha_Llamada.HasValue ?
                new ObjectParameter("Fecha_Llamada", fecha_Llamada) :
                new ObjectParameter("Fecha_Llamada", typeof(System.DateTime));
    
            var follow_UPParameter = follow_UP.HasValue ?
                new ObjectParameter("Follow_UP", follow_UP) :
                new ObjectParameter("Follow_UP", typeof(short));
    
            var estado_Resolucion_LlamadaParameter = estado_Resolucion_Llamada.HasValue ?
                new ObjectParameter("Estado_Resolucion_Llamada", estado_Resolucion_Llamada) :
                new ObjectParameter("Estado_Resolucion_Llamada", typeof(short));
    
            var iD_CLIENTEParameter = iD_CLIENTE.HasValue ?
                new ObjectParameter("ID_CLIENTE", iD_CLIENTE) :
                new ObjectParameter("ID_CLIENTE", typeof(int));
    
            var iD_EMPLEADOParameter = iD_EMPLEADO.HasValue ?
                new ObjectParameter("ID_EMPLEADO", iD_EMPLEADO) :
                new ObjectParameter("ID_EMPLEADO", typeof(int));
    
            var iD_PRODUCTOParameter = iD_PRODUCTO.HasValue ?
                new ObjectParameter("ID_PRODUCTO", iD_PRODUCTO) :
                new ObjectParameter("ID_PRODUCTO", typeof(int));
    
            var iD_PROBLEMAParameter = iD_PROBLEMA.HasValue ?
                new ObjectParameter("ID_PROBLEMA", iD_PROBLEMA) :
                new ObjectParameter("ID_PROBLEMA", typeof(int));
    
            var iD_SOLUCIONParameter = iD_SOLUCION.HasValue ?
                new ObjectParameter("ID_SOLUCION", iD_SOLUCION) :
                new ObjectParameter("ID_SOLUCION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("LLAMADASinsert", iD_LlamadaParameter, fecha_LlamadaParameter, follow_UPParameter, estado_Resolucion_LlamadaParameter, iD_CLIENTEParameter, iD_EMPLEADOParameter, iD_PRODUCTOParameter, iD_PROBLEMAParameter, iD_SOLUCIONParameter);
        }
    
        public virtual ObjectResult<LLAMADASGETALL1_Result1> LLAMADASGETALL1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LLAMADASGETALL1_Result1>("LLAMADASGETALL1");
        }
    
        public virtual ObjectResult<Nullable<int>> GET_ID_CLIENTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GET_ID_CLIENTE");
        }
    
        public virtual ObjectResult<GET_ID_CLIENTE1_Result> GET_ID_CLIENTE1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ID_CLIENTE1_Result>("GET_ID_CLIENTE1");
        }
    
        public virtual ObjectResult<Nullable<int>> GET_ID_EMPLEADO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GET_ID_EMPLEADO");
        }
    
        public virtual ObjectResult<GET_ID_PROBLEMA_Result> GET_ID_PROBLEMA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ID_PROBLEMA_Result>("GET_ID_PROBLEMA");
        }
    
        public virtual ObjectResult<GET_ID_PRODUCTO_Result> GET_ID_PRODUCTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ID_PRODUCTO_Result>("GET_ID_PRODUCTO");
        }
    
        public virtual ObjectResult<GET_ID_SOLUCION_Result> GET_ID_SOLUCION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ID_SOLUCION_Result>("GET_ID_SOLUCION");
        }
    
        public virtual ObjectResult<GET_ID_EMPLEADO1_Result> GET_ID_EMPLEADO1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ID_EMPLEADO1_Result>("GET_ID_EMPLEADO1");
        }
    }
}
