//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALL_CENTER
    {
        public int ID_CALLCENTER { get; set; }
        public string CODIGO_INTERNO { get; set; }
        public string NOMBRE { get; set; }
        public string REGION { get; set; }
        public string PAIS { get; set; }
        public string CODIGO_ZIP { get; set; }
    }
}
