//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int ID_CLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public int CEDULA { get; set; }
        public string GENERO { get; set; }
        public System.DateTime FECHA_DE_NACIMIENTO { get; set; }
        public string DIRECCION { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string ESTADO { get; set; }
    }
}
