//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public int ID_CUENTA { get; set; }
        public string METODO_PAGO { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public string TIPO_CUENTA { get; set; }
        public string DIRECCIONENTREGA { get; set; }
    }
}
