//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int ID_EMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public int CEDULA { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string CODIGO_INTERNO { get; set; }
    }
}
