//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int ID_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public int PRECIO_UNITARIO { get; set; }
        public string CODIGO_PRODUCTO { get; set; }
        public int COSTO_UNITARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ENVIO { get; set; }
    }
}
